import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert } from 'react-native';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';
import { Card } from '../../components/common/Card';
import { Input } from '../../components/common/Input';
import { Button } from '../../components/common/Button';
import { ChevronLeft, Info, Copy } from 'lucide-react-native';
import QRCode from 'react-native-qrcode-svg';
import * as Clipboard from 'expo-clipboard';

const GATEWAYS = [
    { id: '1', name: 'USDT (TRC20)', type: 'crypto', min: 10, max: 10000, fee: '0%' },
    { id: '2', name: 'Bitcoin (BTC)', type: 'crypto', min: 20, max: 10000, fee: '0%' },
    { id: '3', name: 'Perfect Money', type: 'fiat', min: 5, max: 5000, fee: '1.5%' },
    { id: '4', name: 'Payeer', type: 'fiat', min: 5, max: 5000, fee: '1%' },
];

export const DepositScreen: React.FC<any> = ({ navigation }) => {
    const [selectedGatewayId, setSelectedGatewayId] = useState(GATEWAYS[0].id);
    const [amount, setAmount] = useState('');
    const [step, setStep] = useState(1);

    const activeGateway = GATEWAYS.find(g => g.id === selectedGatewayId)!;
    // Mock wallet address generated by backend
    const depositAddress = 'T9yD14Nj9j7xAB4dbGeiX9h8iQjNqA3bZ';

    const handleCopy = async () => {
        await Clipboard.setStringAsync(depositAddress);
        Alert.alert("Copied!", "Deposit address copied.");
    };

    const handleNext = () => {
        const amt = parseFloat(amount);
        if (isNaN(amt) || amt < activeGateway.min || amt > activeGateway.max) {
            Alert.alert("Invalid Amount", `Please enter an amount between $${activeGateway.min} and $${activeGateway.max}.`);
            return;
        }
        setStep(2);
    };

    const handleConfirm = () => {
        Alert.alert(
            "Deposit Initiated",
            "Please ensure you send the exact amount to the provided address. We will credit your account once confirmed on the blockchain.",
            [{ text: "Done", onPress: () => navigation.navigate('WalletHome') }]
        );
    };

    return (
        <View style={styles.container}>
            <View style={styles.header}>
                <TouchableOpacity onPress={() => step === 2 ? setStep(1) : navigation.goBack()} style={styles.backButton}>
                    <ChevronLeft color={colors.textDark} size={28} />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Deposit Funds</Text>
                <View style={{ width: 28 }} />
            </View>

            <ScrollView contentContainerStyle={styles.content}>
                {step === 1 ? (
                    <>
                        <Text style={styles.sectionTitle}>Select Gateway</Text>
                        <View style={styles.gatewaysGrid}>
                            {GATEWAYS.map(gateway => {
                                const isSelected = selectedGatewayId === gateway.id;
                                return (
                                    <TouchableOpacity 
                                        key={gateway.id}
                                        style={[styles.gatewayCard, isSelected && styles.gatewayCardSelected]}
                                        onPress={() => setSelectedGatewayId(gateway.id)}
                                    >
                                        <Text style={[styles.gatewayName, isSelected && { color: colors.primary }]}>{gateway.name}</Text>
                                        <Text style={styles.gatewayLimits}>Min: ${gateway.min}</Text>
                                        <Text style={styles.gatewayFee}>Fee: {gateway.fee}</Text>
                                    </TouchableOpacity>
                                );
                            })}
                        </View>

                        <Text style={styles.sectionTitle}>Deposit Amount</Text>
                        <Input 
                            label="Amount (USD)"
                            placeholder="Enter amount to deposit"
                            keyboardType="numeric"
                            value={amount}
                            onChangeText={setAmount}
                        />

                        <View style={styles.infoBox}>
                            <Info color={colors.primary} size={20} />
                            <Text style={styles.infoText}>
                                Deposits via crypto usually take 5-15 minutes to reflect in your account after network confirmations.
                            </Text>
                        </View>

                        <Button 
                            title="Continue to Payment" 
                            onPress={handleNext}
                            style={styles.nextButton}
                        />
                    </>
                ) : (
                    <>
                        <Card style={styles.qrCard}>
                            <Text style={styles.qrHeader}>Send exactly <Text style={{ color: colors.primary }}>${parseFloat(amount).toFixed(2)}</Text></Text>
                            <Text style={styles.qrSubHeader}>via {activeGateway.name}</Text>

                            <View style={styles.qrWrapper}>
                                <QRCode
                                    value={depositAddress}
                                    size={200}
                                    color={colors.textDark}
                                    backgroundColor={colors.white}
                                />
                            </View>

                            <Text style={styles.addressLabel}>Payment Address</Text>
                            <TouchableOpacity style={styles.addressBox} onPress={handleCopy}>
                                <Text style={styles.addressText} numberOfLines={1} ellipsizeMode="middle">
                                    {depositAddress}
                                </Text>
                                <View style={styles.copyBtn}>
                                    <Copy color={colors.white} size={16} />
                                </View>
                            </TouchableOpacity>

                            <Text style={styles.warningText}>
                                Only send {activeGateway.name} to this address. Sending any other asset will result in permanent loss.
                            </Text>
                        </Card>

                        <Button 
                            title="I have made the payment" 
                            onPress={handleConfirm}
                        />
                    </>
                )}
            </ScrollView>
        </View>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 50,
        paddingBottom: 16,
        paddingHorizontal: 20,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    backButton: { padding: 4 },
    headerTitle: { fontFamily: typography.fonts.display, fontSize: typography.sizes.lg, color: colors.textDark },
    content: { padding: 24 },
    sectionTitle: { fontFamily: typography.fonts.display, fontSize: typography.sizes.lg, color: colors.textDark, marginBottom: 16 },
    gatewaysGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginBottom: 32 },
    gatewayCard: {
        width: '47%',
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        padding: 16,
    },
    gatewayCardSelected: { borderColor: colors.primary, borderWidth: 2, backgroundColor: colors.primaryAccent + '10' },
    gatewayName: { fontFamily: typography.fonts.bodyBold, fontSize: typography.sizes.md, color: colors.textDark, marginBottom: 8 },
    gatewayLimits: { fontFamily: typography.fonts.body, fontSize: typography.sizes.xs, color: colors.textMedium },
    gatewayFee: { fontFamily: typography.fonts.body, fontSize: typography.sizes.xs, color: colors.error, marginTop: 4 },
    infoBox: { flexDirection: 'row', backgroundColor: colors.primaryAccent + '20', padding: 16, borderRadius: 12, gap: 12, marginBottom: 32 },
    infoText: { flex: 1, fontFamily: typography.fonts.body, fontSize: typography.sizes.sm, color: colors.textDark, lineHeight: 20 },
    nextButton: { marginTop: 16 },
    qrCard: { alignItems: 'center', padding: 24, marginBottom: 24 },
    qrHeader: { fontFamily: typography.fonts.display, fontSize: typography.sizes.xl, color: colors.textDark, textAlign: 'center' },
    qrSubHeader: { fontFamily: typography.fonts.body, fontSize: typography.sizes.md, color: colors.textMedium, textAlign: 'center', marginBottom: 24 },
    qrWrapper: { padding: 16, backgroundColor: colors.white, borderRadius: 16, borderWidth: 1, borderColor: colors.border, marginBottom: 32 },
    addressLabel: { fontFamily: typography.fonts.bodyBold, fontSize: typography.sizes.sm, color: colors.textMedium, alignSelf: 'flex-start', marginBottom: 8 },
    addressBox: { flexDirection: 'row', alignItems: 'center', width: '100%', backgroundColor: colors.offWhite, borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingLeft: 16, paddingRight: 4, paddingVertical: 4, marginBottom: 24 },
    addressText: { flex: 1, fontFamily: typography.fonts.mono, fontSize: typography.sizes.sm, color: colors.textDark },
    copyBtn: { backgroundColor: colors.primary, width: 40, height: 40, borderRadius: 8, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
    warningText: { fontFamily: typography.fonts.body, fontSize: typography.sizes.sm, color: colors.error, textAlign: 'center', backgroundColor: '#FEE2E2', padding: 12, borderRadius: 8 }
});
